# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModPriv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='all', max_length=128)),
                ('level', models.IntegerField(default=3)),
                ('pubkey', models.CharField(editable=False, max_length=256)),
            ],
        ),
    ]
